"""Initial migration

Revision ID: 19a035af425b
Revises: 
Create Date: 2024-10-15 23:28:00.111560

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19a035af425b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        # Step 1: Add the 'year' column allowing NULLs
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        # Step 2: Add the 'round' column allowing NULLs
        batch_op.add_column(sa.Column('round', sa.String(length=50), nullable=True))

    # Step 3: Update existing records to set default values
    op.execute("UPDATE candidate SET year = 2023 WHERE year IS NULL")
    op.execute("UPDATE candidate SET round = 'default_round' WHERE round IS NULL")  # Set a default value for 'round'

    # Step 4: Alter columns to make them NOT NULL
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('year', nullable=False)
        batch_op.alter_column('round', nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('round')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
